spring.application.name=vibeshelf-backend

# ===============================
# Database (PostgreSQL - Neon)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-cool-resonance-atvcle9r.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# ===============================
# CSV Import (DISABLED)
# ===============================
app.import.force=false

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.mail.enabled=false
management.health.redis.enabled=false

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=false

# ===============================
# Ollama Configuration
# ===============================
ollama.api.url=http://localhost:11434/api/generate
ollama.model=mistral
ollama.temperature=0.85
ollama.timeout-ms=180000

# ===============================
# GROQ Configuration
# ===============================
groq.api-key=${GROQ_API_KEY}
groq.api-url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant

# ===============================
# Caching Configuration
# ===============================
vibeshelf.cache.ttl-minutes=60
vibeshelf.cache.max-size=500

spring.config.import=optional:configtree:/run/secrets/
# ===============================
# Gmail SMTP
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shreyajamwal19@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
